language: java

sudo: false # Faster builds

env:
  global:
  - JVMLang=Kotlin

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
      addons:
        apt:
          packages:
            - oracle-java9-installer
            - oracle-java9-set-default
      env: JDK_JAVA_OPTIONS='--permit-illegal-access'
      # JDK_JAVA_OPTIONS='--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED'
  allow_failures:
    - jdk: oraclejdk9

before_script:
  - chmod +x gradlew

script:
  - ./gradlew jacocoTestReport makeExecutable --no-daemon --scan

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)