info:
  build:
    name: ${name}
    author: ${appAuthor}
    description: ${description}
    version: ${version}
    java-version: ${javaVersion}
    kotlin-version: ${kotlinVersion}
    kotlinx-version: ${kotlinxVersion}
    spring-boot-version: ${springBootVersion}